      - name: Obfuscate Code
        run: |
          # 提取 import 语句，防止混淆器破坏 ES Module 导入机制
          grep "^import" _worker.js > imports.js || true
          sed -i '/^import/d' _worker.js || true
          
          # 混淆剩下的主体代码（关闭修改全局变量选项，防止破坏 export default）
          javascript-obfuscator _worker.js --output _worker_temp.js --compact true --string-array true --string-array-encoding 'base64' --rename-globals false
          
          # 将头部 import 和混淆后的代码重新拼装
          cat imports.js > _worker_obf.js
          cat _worker_temp.js >> _worker_obf.js
          echo "代码混淆加密完成！"
